# Generated by Django 2.2.7 on 2019-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTrabColab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
